live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Windowed"
opacity = 0.97

[window.dimensions]
columns = 100
lines = 26

[window.padding]
x = 5
y = 3

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[bell]
animation = "EaseOutQuint"
duration = 10

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false

