#!/bin/sh
# lazy lad this 
eval $(/opt/homebrew/bin/brew shellenv)
eval "$(zoxide init zsh)"

fpath+=("$(brew --prefix)/share/zsh/site-functions")
zstyle :prompt:pure:path color white

# Sets and unsets 
unsetopt BEEP
setopt appendhistory
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS

export XDG_RUNTIME_DIR="$HOME/.config"
export DOCKER_CONFIG="$XDG_RUNTIME_DIR/docker"

# Environment variables set everywhere
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
export EDITOR="nvim"
export TERMINAL="iterm2"
export BROWSER="brave"
export TERM="xterm-256color"
export HISTFILE=~/.config/zsh/.zsh_history
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=008'

export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"


export ANDROID_AVD_HOME="$XDG_RUNTIME_DIR/android"
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

export GOBIN="$HOME/.local/bin"

export DOTFILES="/Users/$USER/.dotfiles/"
# export TMUX_CONFIG="$XDG_RUNTIME_DIR/tmux/.tmux.conf"
export NOTES="/Users/$USER/Notes/"
export DEV_FILES="/Users/$USER/Developer"
export LG_CONFIG_FILE="$HOME/.config/lazygit/config.yml"
export FZF_DEFAULT_COMMAND='fd --type f'
export CHROME_EXECUTABLE="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"
export FZF_COMPLETION_TRIGGER='--'
export RUST_BACKTRACE=0

export GIT_CONFIG_GLOBAL="$HOME/.config/git/.gitconfig"

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 

# . "$HOME/.cargo/env"

