#!/bin/sh
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$PATH:/Users/mariocampbell/Dev/flutter/bin"
export PATH="$PATH:$HOME/.local/bin"

export GOBIN="$HOME/.local/bin"

export DOTFILES="/Users/mariocampbell/.dotfiles/"
export NOTES="/Users/mariocampbell/Notes/"
export DEV_FILES="/Users/mariocampbell/Dev/lab"

export LG_CONFIG_FILE="$HOME/.config/lazygit/config.yml"
export FZF_DEFAULT_COMMAND='fd --type f'

export AWS_ACCESS_KEY_ID='AKIAVHCW2T3HQE7DBV7E'
export AWS_SECRET_ACCESS_KEY='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'
export AWS_DEFAULT_REGION='us-west-2'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
