#!/bin/sh

export NPM_TOKEN=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
export DOCKER_CLIENT_TIMEOUT=600
export COMPOSE_HTTP_TIMEOUT=600
export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig"
  
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(direnv hook zsh)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export LDFLAGS="-L/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/jpeg/lib"  
export CPPFLAGS="-I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/jpeg/include" 
export CFLAGS="-Wno-error=implicit-function-declaration" 
export GRPC_BUILD_WITH_BORING_SSL_ASM="" 
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true
