require "mcampbellr.core.sets"
require "mcampbellr.core.colorscheme"
require "mcampbellr.core.commands"

require "mcampbellr.plugins"
require "mcampbellr.cmp"
require "mcampbellr.lsp"
require "mcampbellr.debugger"
require "mcampbellr.autocommands"
require "mcampbellr.telescope"
