require "mcampbellr.core.sets"
require "mcampbellr.core.theme"
require "mcampbellr.core.commands"
require "mcampbellr.core.plugins"

require "mcampbellr.utils"
require "mcampbellr.cmp"
require "mcampbellr.lsp"
require "mcampbellr.dap"
require "mcampbellr.autocommands"
require "mcampbellr.telescope"
